### ISSUE TITLE
Version 1.3.1 has mutliple vulnerabilities in urllib3 dependency

### ISSUE THREAD

**Issue by ghost** [Turall/OPA-python-client#11]
As title says, the latest version hosted in pypi depends on a version of `urllib3` that has multiple CVEs filed against it. This seems to already be fixed at the tip of `origin/master`, could you push a new version to pypi with that updated dependency? We'd love to continue using this project w/o having to fork it for security compliance.

**Comment by Turall** [comment]
Hi @tsweeney-dust , Thanks for the report! I updated dependencies and released a new version.
