### ISSUE TITLE
New release to resolve security vulnerability

### ISSUE THREAD

**Issue by willarmiros** [Turall/OPA-python-client#21]
Hello - #20 was made to resolve a security vulnerability. It would be great if this PR could be included in a release so that consumers of opa-python-client can resolve the vulnerability too.

**Comment by Turall** [comment]
@willarmiros Sorry for the late response. I Released the new version 1.3.6

**Comment by limolitz** [comment]
The 1.3.6 version didn't land on pypi, I think that's due to the pipeline failing. Can you check that?
