### ISSUE TITLE
Relax requirements to allow urllib3 >=2.0.0

### ISSUE THREAD

**Issue by limolitz** [Turall/OPA-python-client#24]
It seems like this library already runs on urllib3 2.0.6 if I read the poetry file correctly, but it doesn't announce its support in `pyproject.toml` and depends on a 1.X version.

Would be great if this could be changed, we're starting to run into issues with other packages requiring a 2.X version.

**Comment by Turall** [comment]
Hi @limolitz thank you for your interest in this project. I updated the dependencies and released a new version. You can install it on pypi https://pypi.org/project/opa-python-client/
