### ISSUE TITLE
1.3.6 on pypi seems to still have the wrong dependencies pinned

### ISSUE THREAD

**Issue by cbrand** [Turall/OPA-python-client#25]
Hello,

I just ran into the issue I thought to have  fixed with https://github.com/Turall/OPA-python-client/pull/20

It seems the certifi dependency is on the 1.3.6 version still pinned in the PKG-INFO doc and probably requires a new release to fix it.

Extracting the 1.3.6 version from pypi includes the following the PKG-INFO (not including the README info):

```
Metadata-Version: 2.1
Name: opa-python-client
Version: 1.3.6
Summary: Client for connection to the OPA service
Home-page: https://github.com/Turall/OPA-python-client
License: MIT
Author: Tural Muradov
Author-email: tural_m@hotmail.com
Requires-Python: >=3.9,<4.0
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: MIT License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.12
Classifier: Programming Language :: Python :: 3 :: Only
Requires-Dist: certifi (>=2023.11.17,<2024.0.0)
Requires-Dist: requests (>=2.31.0,<3.0.0)
Requires-Dist: urllib3 (>=2.1.0,<3.0.0)
Requires-Dist: user-agent (>=0.1.10,<0.2.0)
Project-URL: Repository, https://github.com/Turall/OPA-python-client
```

The certifi and urllib3 dependencies are both pinned to wrong versions and not correct according to https://github.com/Turall/OPA-python-client/blob/master/pyproject.toml

Could you double check the release pipeline and release a fixed 1.3.7 version?

**Comment by Turall** [comment]
@cbrand thank you for your interest in this project. I released a new version 1.6.7
